apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: portfolio
type: Opaque
stringData:
  # Le @ du mot de passe DOIT etre encode en %40 dans l URI MongoDB
  # Sinon MongoDB interprete "sser123" comme le hostname -> EAI_AGAIN
  MONGODB_URI: "mongodb://mn2243d_db_user:P%40sser123@mongodb-service:27017/portfolio_db?authSource=admin"
  JWT_SECRET: MyUltraStrongSecretKey!2026
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: portfolio
type: Opaque
stringData:
  username: mn2243d_db_user
  password: "P@sser123"
